# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-01 14:24
from __future__ import unicode_literals

from os.path import basename
from django.db import migrations


def update_source_url(source):
    # Get the filename, and attach the new s3 path to it.
    filename = basename(source.url)
    new_url = 'https://s3.amazonaws.com/' + \
              'ccnmtl-digitaltibet-static-prod/objects/' + filename
    source.url = new_url
    source.save()


def update_all_dtibet_urls(apps, schema_editor):
    Source = apps.get_model('assetmgr', 'Source')
    sources = Source.objects.filter(
        url__startswith='http://digitaltibet.ccnmtl.columbia.edu')
    for source in sources:
        update_source_url(source)


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgr', '0008_auto_20171127_1409'),
    ]

    operations = [
        migrations.RunPython(update_all_dtibet_urls),
    ]
