# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgr', '0010_auto_20180221_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='metadata_blob',
            field=models.TextField(blank=True, help_text='Be careful, this is a JSON blob and NOT a place to enter the description, etc, and is easy to format incorrectly. Make sure not to add any "\'s.'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='source',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
