# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-20 13:54
from __future__ import unicode_literals

from django.db import migrations


def update_wardenclyffe_urls(apps, schema_editor):
    ExternalCollection = apps.get_model('assetmgr', 'ExternalCollection')
    for ec in ExternalCollection.objects.all():
        if ec.url and ('wardenclyffe.ccnmtl' in ec.url):
            new_url = ec.url.replace(
                'wardenclyffe.ccnmtl', 'wardenclyffe.ctl')
            ec.url = new_url
            ec.save()

        if ec.thumb_url and ('wardenclyffe.ccnmtl' in ec.thumb_url):
            new_thumb = ec.thumb_url.replace(
                'wardenclyffe.ccnmtl', 'wardenclyffe.ctl')
            ec.thumb_url = new_thumb
            ec.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgr', '0011_auto_20190916_1639'),
    ]

    operations = [
        migrations.RunPython(update_wardenclyffe_urls),
    ]
