# Generated by Django 2.2.24 on 2021-07-01 14:13

from django.db import migrations
import mediathread.assetmgr.custom_storage
import mediathread.assetmgr.models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgr', '0012_auto_20191220_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='upload',
            field=mediathread.assetmgr.models.S3PrivateFileField(blank=True, storage=mediathread.assetmgr.custom_storage.S3PrivateStorage(), upload_to='uploads/'),
        ),
    ]
