# Generated by Django 3.2.16 on 2022-10-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgr', '0013_source_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='media_type',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
