# Generated by Django 3.2.16 on 2022-10-21 16:54

from django.db import migrations


def fix_panopto_thumbnails(apps, schema_editor):
    Source = apps.get_model('assetmgr', 'Source')
    badprefix = 'https://columbia.hosted.panopto.comhttps://'
    sources = Source.objects.filter(
        url__startswith=badprefix, label='thumb')

    for source in sources:
        source.url = source.url.replace(badprefix, 'https://')
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgr', '0014_alter_source_media_type'),
    ]

    operations = [
        migrations.RunPython(fix_panopto_thumbnails),
    ]
