# Generated by Django 3.2.16 on 2022-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmgr', '0015_auto_20221021_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='transcript',
            field=models.TextField(blank=True, help_text='Transcript for audio/video media', null=True),
        ),
    ]
