db:
  image: postgres
  environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
web:
  image: ccnmtl/mediathread
  environment:
    - SETTINGS=settings_compose
  command: manage runserver 0.0.0.0:8000
  volumes:
    - .:/app/
  ports:
    - "8000:8000"
  links:
    - db
