# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuredcollaboration', '0005_auto_20151106_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
