# Generated by Django 2.2.14 on 2020-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuredcollaboration', '0006_auto_20180907_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='object_pk',
            field=models.IntegerField(blank=True, null=True, verbose_name='object ID'),
        ),
    ]
