# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosherd', '0004_auto_20170508_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sherdnote',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='sherdnote',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
