# Generated by Django 2.2.24 on 2021-11-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosherd', '0005_auto_20190916_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_global_annotation',
            field=models.BooleanField(default=False),
        ),
    ]
