# Generated by Django 2.2.24 on 2021-11-03 16:03

from django.db import migrations
from django.db.models import Q


def migrate_is_global_annotation(apps, schema_editor):
    Annotation = apps.get_model('djangosherd', 'Annotation')
    for a in Annotation.objects.filter(
            Q(range1__isnull=True) & Q(range2__isnull=True)):
        a.is_global_annotation = True
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('djangosherd', '0006_annotation_is_global_annotation'),
    ]

    operations = [
        migrations.RunPython(migrate_is_global_annotation),
    ]
