# Generated by Django 2.2.16 on 2020-09-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_panoptoingestlogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoptoingestlogentry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseaffils.Course'),
        ),
    ]
