# Generated by Django 2.2.16 on 2020-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200917_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoptoingestlogentry',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
